version: "3.8"
services:
  edge-nginx:
    image: nginx:1.25-alpine
    container_name: edge-nginx
    restart: always
    ports:
      - "8081:8081"
    networks:
      - appnet
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d
networks:
  appnet:
    external: true
